todosubject/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

todosubject/todo_board/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo_board'

urlpatterns = [
    url(r'^$', views.todo_board.as_view(), name='todo_board'),
]

todosubject/todo_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo_main'

urlpatterns = [
    url(r'^$', views.todo_main.as_view(), name='todo_main'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todosubject/todo_board/models.py
from django.conf import settings
from django.db import models

# Create your models here.
# from user.models import User
# from ..user.models import User
# from todosubject.user.models import User

# from user.models import User
user = settings.AUTH_USER_MODEL


class ProjectCode(models.Model):
    name = models.CharField('p_name', max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class TodoList(models.Model):
    pcode = models.ForeignKey(ProjectCode, on_delete=models.CASCADE)
    user = models.ForeignKey(user, related_name='user_todo_list', on_delete=models.CASCADE)
    title = models.CharField('제목', max_length=20)
    contents = models.TextField('내용', null=True, blank=True)
    is_complete = models.BooleanField('완료여부', default=False)
    end_date = models.DateField('완료일', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # class Meta:
    #     managed=False
    #     db_table =

todosubject/todo_main/models.py
from django.db import models

# Create your models here.

todosubject/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
# from todosubject.common import TodoBase


class User(AbstractUser):
    name = models.CharField('이름', max_length=10)
    email = models.EmailField('email')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

todosubject/todo_board/forms.py
from django import forms

from todo_board.models import TodoList


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = {'title', 'content', 'end_date'}

todosubject/todo_board/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic

from todo_board.models import TodoList


class todo_board(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'todo_board/todo_list.html'
        todo_list = TodoList.objects.all()
        return render(request, template_name,{'todo_list':todo_list})

todosubject/todo_main/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic


class todo_main(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'todo_main/index.html'
        return render(request, template_name)

todosubject/user/views.py
from django.shortcuts import render

# Create your views here.

todosubject/templates/todo_board/todo_list.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
    <div class="col-md-12">
        <div class="container">
            <h1>할일을 적어봅시다 </h1>
            <div id="example1" class="list-group col">
                {% for list in todo_list %}
                    <div class="list-group-item">
                        <input type="checkbox" name="{{ list.title }} " value="{{ list.contents }}">
                        {{ list.title }} <br></div>
                {% endfor %}
                <p></p>
            </div>

            <button type="button" class="btn btn-primary"
                    onclick="location.href='{% url 'todo_board:todo_board' %}'">일정추가
            </button>
        </div>
    </div>
{% endblock %}

todosubject/templates/todo_main/common/header.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Fontawesom-->
    {#    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">#}

    <!--Animated CSS-->
    {#    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">#}

    <!-- Bootstrap -->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <!--Bootstrap Carousel-->
    {#    <link type="text/css" rel="stylesheet" href="{% static 'css/carousel.css' %}"/>#}

    {#    <link rel="stylesheet" href="{% static 'css/isotope/style.css' %}">#}

    <!--Main Stylesheet-->
    {#    <link href="{% static 'css/style.css' %}" rel="stylesheet">#}
    <!--Responsive Framework-->
    {#    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">#}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>Document</title>
    <style type="text/css">
        #container {
            min-width: 310px;
            max-width: 800px;
            height: 400px;
            margin: 0 auto
        }

        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }

        .list-group-item {
            width: 40%;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'todo_main:todo_main' %}">todo main</a></li>
{#            <li><a href="{% url 'todo_board:todo_board' %}">todo list</a></li>#}
        </ul>
    </div>
</nav>
{% block main %}

{% endblock main %}
</body>
<script src="{% static 'js/Sortable.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script>
    new Sortable(todo_list_endDate, {
        animation: 150,
        ghostClass: 'blue-background-class'
    });
    new Sortable(todo_list_no_endDate, {
        animation: 150,
        ghostClass: 'blue-background-class'
    });


</script>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

{#<script>#}
{#    function prioirty_save() {#}
{#        todo_list = $(".list-group-item");#}
{#        todo_dict = {}#}
{#        for (var i = 0; i < todo_list.length; i++) {#}
{#            todo_dict[todo_list[i].getAttribute("div_pk")] = i + 1#}
{#        }#}
{#        console.log(todo_dict);#}
{#        $.ajax({#}
{#            type: "POST",#}
{#            url: "{% url 'todo_board:todo_board_save_priority' %}",#}
{#            data: {'todo_dict': JSON.stringify(todo_dict), 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#            dataType: "json",#}
{#            success: function (response) {#}
{#                console.log("성공");#}
{#                window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#            },#}
{#            error: function (request, status, error) {#}
{#                console.log("실패.");#}
{#            },#}
{#        });#}
{#    }#}
{#</script>#}

{#<script>#}
{#    completed = document.getElementsByName('complete');#}
{#    for (var i = 0; i < completed.length; i++) {#}
{#        completed[i].checked = true;#}
{#    }#}
{##}
{#    $("input[name*=complete]").change(function () {#}
{#        if ($(this).is(":checked")) {#}
{#            pk = $(this).attr("pk");#}
{#            $.ajax({#}
{#                type: "POST",#}
{#                url: "{% url 'todo_board:todo_board_is_complete' %}",#}
{#                data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#                dataType: "json",#}
{#                success: function (response) {#}
{#                    console.log("성공");#}
{#                    window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#                },#}
{#                error: function (request, status, error) {#}
{#                    console.log("실패.");#}
{#                },#}
{#            });#}
{#        }#}
{#        //체크박스 해제#}
{#        else {#}
{#            pk = $(this).attr("pk");#}
{#            $.ajax({#}
{#                type: "POST",#}
{#                url: "{% url 'todo_board:todo_board_is_non_complete' %}",#}
{#                data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#                dataType: "json",#}
{#                success: function (response) {#}
{#                    window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#                },#}
{#                error: function (request, status, error) {#}
{#                    console.log("실패.");#}
{#                },#}
{#            });#}
{#        }#}
{#    });#}
{##}
{#</script>#}
</html>

todosubject/templates/todo_main/index.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
    <div class="col-md-12">
        <div class="container">
            <h1>할일들을 적어봅시다 </h1>
            <p></p>
        </div>
    </div>
{% endblock %}

todosubject/todo_main/templates/todo_main/common/header.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Fontawesom-->
    {#    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">#}

    <!--Animated CSS-->
    {#    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">#}

    <!-- Bootstrap -->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <!--Bootstrap Carousel-->
    {#    <link type="text/css" rel="stylesheet" href="{% static 'css/carousel.css' %}"/>#}

    {#    <link rel="stylesheet" href="{% static 'css/isotope/style.css' %}">#}

    <!--Main Stylesheet-->
    {#    <link href="{% static 'css/style.css' %}" rel="stylesheet">#}
    <!--Responsive Framework-->
    {#    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">#}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>Document</title>
    <style type="text/css">
        #container {
            min-width: 310px;
            max-width: 800px;
            height: 400px;
            margin: 0 auto
        }

        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }

        .list-group-item {
            width: 40%;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'todo_main:todo_main' %}">todo main</a></li>
            {#            <li><a href="{% url 'todo_board:todo_board' %}">todo list</a></li>#}
        </ul>
    </div>
</nav>
{% block main %}

{% endblock main %}
</body>
<script src="{% static 'js/Sortable.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script>
    new Sortable(todo_list_endDate, {
        animation: 150,
        ghostClass: 'blue-background-class'
    });
    new Sortable(todo_list_no_endDate, {
        animation: 150,
        ghostClass: 'blue-background-class'
    });


</script>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

{#<script>#}
{#    function prioirty_save() {#}
{#        todo_list = $(".list-group-item");#}
{#        todo_dict = {}#}
{#        for (var i = 0; i < todo_list.length; i++) {#}
{#            todo_dict[todo_list[i].getAttribute("div_pk")] = i + 1#}
{#        }#}
{#        console.log(todo_dict);#}
{#        $.ajax({#}
{#            type: "POST",#}
{#            url: "{% url 'todo_board:todo_board_save_priority' %}",#}
{#            data: {'todo_dict': JSON.stringify(todo_dict), 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#            dataType: "json",#}
{#            success: function (response) {#}
{#                console.log("성공");#}
{#                window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#            },#}
{#            error: function (request, status, error) {#}
{#                console.log("실패.");#}
{#            },#}
{#        });#}
{#    }#}
{#</script>#}

{#<script>#}
{#    completed = document.getElementsByName('complete');#}
{#    for (var i = 0; i < completed.length; i++) {#}
{#        completed[i].checked = true;#}
{#    }#}
{##}
{#    $("input[name*=complete]").change(function () {#}
{#        if ($(this).is(":checked")) {#}
{#            pk = $(this).attr("pk");#}
{#            $.ajax({#}
{#                type: "POST",#}
{#                url: "{% url 'todo_board:todo_board_is_complete' %}",#}
{#                data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#                dataType: "json",#}
{#                success: function (response) {#}
{#                    console.log("성공");#}
{#                    window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#                },#}
{#                error: function (request, status, error) {#}
{#                    console.log("실패.");#}
{#                },#}
{#            });#}
{#        }#}
{#        //체크박스 해제#}
{#        else {#}
{#            pk = $(this).attr("pk");#}
{#            $.ajax({#}
{#                type: "POST",#}
{#                url: "{% url 'todo_board:todo_board_is_non_complete' %}",#}
{#                data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#                dataType: "json",#}
{#                success: function (response) {#}
{#                    window.location.href = "{% url 'todo_board:todo_board' %}"#}
{#                },#}
{#                error: function (request, status, error) {#}
{#                    console.log("실패.");#}
{#                },#}
{#            });#}
{#        }#}
{#    });#}
{##}
{#</script>#}
</html>

todosubject/todo_main/templates/todo_main/index.html
<<<<<<< HEAD
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
    <div class="col-md-12">
        <div class="container">
            <h1>Main Page</h1>
            <p></p>
        </div>
    </div>
{% endblock %}
=======
메인입니다.
>>>>>>> 9d800abd2c45d901e8788f710bbb3d0cb8473384